(let ([x 5])
    (begin 
        (set! x (+ 10 (read)))
        (read)
        (let ([y (read)]) 
            (if (< y 10)
                (+ x y)
                (+ (- y 10) x)
            )
        )
    )
)
